# Generated by Django 5.0.3 on 2024-09-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_inputfield_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
